services:
  - type: web
    name: helios-academic-hub
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_NAME
        value: Helios University Academic Hub
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MYSQL_SSL_MODE
        value: verify-ca
      - key: MYSQL_SSL_CA
        sync: false
      - key: AIVEN_CA_CERT_BASE64
        sync: false
      - key: HELIOS_SECRET_KEY
        generateValue: true
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: SMTP_FROM_NAME
        value: Helios University Academic Hub
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_VERIFY_SERVICE_SID
        sync: false
